version: '2'

services:
    logservice1:
        image: angiemeg/logservice
        container_name: logservice1
        ports:
            - "35001:6001"
        depends_on:
            - db

    logservice2:
        image: angiemeg/logservice
        container_name: logservice2
        ports:
            - "35002:6001"
        depends_on:
            - db

    logservice3:
        image: angiemeg/logservice
        container_name: logservice3
        ports:
            - "35003:6001"
        depends_on:
            - db

    roundrobin:
        image: angiemeg/lbroundrobin
        container_name: lbroundrobin
        ports:
            - "35000:6000"
        depends_on:
            - logservice1
            - logservice2
            - logservice3

    db:
        image: mongo:3.6.1
        container_name: db
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
        
volumes:
    mongodb:
    mongodb_config: