version: '2'

services:
    logservice:
        image: angiemeg/logservice
        container_name: logservice
        ports:
            - "35000:6000"
        depends_on:
            - db-mongo

    roundrobin:
        image: angiemeg/roundrobin
        container_name: lbroundrobin
        ports:
            - "35001-35003:6000"
        depends_on:
            - logservice

    db-mongo:
        image: mongo:3.6.1
        container_name: db-mongo
        volumes:
            - mongodb:/data/db
            - mongodb_config:/data/configdb
        ports:
            - 27017:27017
        command: mongod
volumes:
    mongodb:
    mongodb_config: